//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaplampaAdmin.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Countries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Countries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NaplampaAdmin.GlobalResources.Countries", typeof(Countries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausztria.
        /// </summary>
        public static string LOC_AUSTRIA {
            get {
                return ResourceManager.GetString("LOC_AUSTRIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium.
        /// </summary>
        public static string LOC_BELGIUM {
            get {
                return ResourceManager.GetString("LOC_BELGIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnország.
        /// </summary>
        public static string LOC_FINLAND {
            get {
                return ResourceManager.GetString("LOC_FINLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franciaország.
        /// </summary>
        public static string LOC_FRANCE {
            get {
                return ResourceManager.GetString("LOC_FRANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Németország.
        /// </summary>
        public static string LOC_GERMANY {
            get {
                return ResourceManager.GetString("LOC_GERMANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görögország.
        /// </summary>
        public static string LOC_GREECE {
            get {
                return ResourceManager.GetString("LOC_GREECE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magyarország.
        /// </summary>
        public static string LOC_HUNGARY {
            get {
                return ResourceManager.GetString("LOC_HUNGARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to íroszág.
        /// </summary>
        public static string LOC_IRELAND {
            get {
                return ResourceManager.GetString("LOC_IRELAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olaszország.
        /// </summary>
        public static string LOC_ITALY {
            get {
                return ResourceManager.GetString("LOC_ITALY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxemburg.
        /// </summary>
        public static string LOC_LUXEMBOURG {
            get {
                return ResourceManager.GetString("LOC_LUXEMBOURG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hollandia.
        /// </summary>
        public static string LOC_NETHERLANDS {
            get {
                return ResourceManager.GetString("LOC_NETHERLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugália.
        /// </summary>
        public static string LOC_PORTUGAL {
            get {
                return ResourceManager.GetString("LOC_PORTUGAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szlovákia.
        /// </summary>
        public static string LOC_SLOVAKIA {
            get {
                return ResourceManager.GetString("LOC_SLOVAKIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szlovénia.
        /// </summary>
        public static string LOC_SLOVENIA {
            get {
                return ResourceManager.GetString("LOC_SLOVENIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanyolország.
        /// </summary>
        public static string LOC_SPAIN {
            get {
                return ResourceManager.GetString("LOC_SPAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svájc.
        /// </summary>
        public static string LOC_SWITZERLAND {
            get {
                return ResourceManager.GetString("LOC_SWITZERLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyesült Kiralyság.
        /// </summary>
        public static string LOC_UK {
            get {
                return ResourceManager.GetString("LOC_UK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyesült Államok.
        /// </summary>
        public static string LOC_USA {
            get {
                return ResourceManager.GetString("LOC_USA", resourceCulture);
            }
        }
    }
}
