//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaplampaAdmin.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Currencies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Currencies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NaplampaAdmin.GlobalResources.Currencies", typeof(Currencies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svájci frank.
        /// </summary>
        internal static string LOC_CHF {
            get {
                return ResourceManager.GetString("LOC_CHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euró.
        /// </summary>
        internal static string LOC_EUR {
            get {
                return ResourceManager.GetString("LOC_EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angol font.
        /// </summary>
        internal static string LOC_GBP {
            get {
                return ResourceManager.GetString("LOC_GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magyar forint.
        /// </summary>
        internal static string LOC_HUF {
            get {
                return ResourceManager.GetString("LOC_HUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amerikai dollár.
        /// </summary>
        internal static string LOC_USD {
            get {
                return ResourceManager.GetString("LOC_USD", resourceCulture);
            }
        }
    }
}
