//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaplampaAdmin.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderStatuses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderStatuses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NaplampaAdmin.GlobalResources.OrderStatuses", typeof(OrderStatuses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ismeretlen.
        /// </summary>
        public static string ORDERSTATUS_0 {
            get {
                return ResourceManager.GetString("ORDERSTATUS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rögzítve.
        /// </summary>
        public static string ORDERSTATUS_1 {
            get {
                return ResourceManager.GetString("ORDERSTATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postázásra kész.
        /// </summary>
        public static string ORDERSTATUS_15 {
            get {
                return ResourceManager.GetString("ORDERSTATUS_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postázva, fizetve, garis csere.
        /// </summary>
        public static string ORDERSTATUS_159 {
            get {
                return ResourceManager.GetString("ORDERSTATUS_159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garanciális kérelem.
        /// </summary>
        public static string ORDERSTATUS_191 {
            get {
                return ResourceManager.GetString("ORDERSTATUS_191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postázva, visszaküldött.
        /// </summary>
        public static string ORDERSTATUS_2075 {
            get {
                return ResourceManager.GetString("ORDERSTATUS_2075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postázva, fizetve, visszaküldött.
        /// </summary>
        public static string ORDERSTATUS_2079 {
            get {
                return ResourceManager.GetString("ORDERSTATUS_2079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garanciális kérelem.
        /// </summary>
        public static string ORDERSTATUS_223 {
            get {
                return ResourceManager.GetString("ORDERSTATUS_223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postázva, pénzre várva.
        /// </summary>
        public static string ORDERSTATUS_27 {
            get {
                return ResourceManager.GetString("ORDERSTATUS_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postázásra kész (Garanciális).
        /// </summary>
        public static string ORDERSTATUS_271 {
            get {
                return ResourceManager.GetString("ORDERSTATUS_271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postázva (Garanciális).
        /// </summary>
        public static string ORDERSTATUS_287 {
            get {
                return ResourceManager.GetString("ORDERSTATUS_287", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fizetési teljesítésre vár.
        /// </summary>
        public static string ORDERSTATUS_3 {
            get {
                return ResourceManager.GetString("ORDERSTATUS_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postázva, fizetve.
        /// </summary>
        public static string ORDERSTATUS_31 {
            get {
                return ResourceManager.GetString("ORDERSTATUS_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kézbesítve, fizetve.
        /// </summary>
        public static string ORDERSTATUS_63 {
            get {
                return ResourceManager.GetString("ORDERSTATUS_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postázásra kész (UV).
        /// </summary>
        public static string ORDERSTATUS_9 {
            get {
                return ResourceManager.GetString("ORDERSTATUS_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Véleménykérés elküldve.
        /// </summary>
        public static string ORDERSTATUS_95 {
            get {
                return ResourceManager.GetString("ORDERSTATUS_95", resourceCulture);
            }
        }
    }
}
