//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaplampaAdmin.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PaymentMethods {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentMethods() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NaplampaAdmin.GlobalResources.PaymentMethods", typeof(PaymentMethods).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ismeretlen.
        /// </summary>
        public static string PAYMENTMETHOD_0 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banki átutalás.
        /// </summary>
        public static string PAYMENTMETHOD_1 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal.
        /// </summary>
        public static string PAYMENTMETHOD_2 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankkártya.
        /// </summary>
        public static string PAYMENTMETHOD_3 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postai utánvétel.
        /// </summary>
        public static string PAYMENTMETHOD_4 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Készpénz.
        /// </summary>
        public static string PAYMENTMETHOD_5 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitCoin.
        /// </summary>
        public static string PAYMENTMETHOD_6 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwolla.
        /// </summary>
        public static string PAYMENTMETHOD_7 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneybookers.
        /// </summary>
        public static string PAYMENTMETHOD_8 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_8", resourceCulture);
            }
        }
    }
}
