//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EmailTemplates", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;en&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body lang=&quot;en&quot;&gt;
        ///
        ///Dear {0}!&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///Christmas is coming, but we just can&apos;t wait until the day, so we decided to give You a present right now! Please accept our extra 5% discount coupon code which can be used between 1st and 25th of December this year!&lt;br /&gt;
        ///Your code is &apos;MLCH09&apos;. (You need to enter the code during your order on the first screen. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CHRISTMAS2009_BODY {
            get {
                return ResourceManager.GetString("CHRISTMAS2009_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagmaLight - Christmas Coupon for You!.
        /// </summary>
        internal static string CHRISTMAS2009_SUBJECT {
            get {
                return ResourceManager.GetString("CHRISTMAS2009_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;en&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body lang=&quot;en&quot;&gt;
        ///
        ///Dear {0}!&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///You need to confirm your e-mail address in order to make the communication channel more secure and to access our web site&apos;s special functions. Please click on the link below.&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;a href=&quot;http://www.magmalight.com/Admin/ConfirmEmail.aspx?Email={1}&amp;ConfirmationCode={2}&quot;&gt;E-mail  confirmation HERE&lt;/a&gt;.&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CONFIRMEMAIL_BODY {
            get {
                return ResourceManager.GetString("CONFIRMEMAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagmaLight - E-mail confirmation.
        /// </summary>
        internal static string CONFIRMEMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("CONFIRMEMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagmaLight - System message.
        /// </summary>
        internal static string DEFAULT_SUBJECT {
            get {
                return ResourceManager.GetString("DEFAULT_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;en&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body lang=&quot;en&quot;&gt;
        ///
        ///Dear Webmaster!&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///Something is wrong with the system!
        ///&lt;br /&gt;&lt;br /&gt;
        ///{0}&lt;br /&gt;&lt;br /&gt;
        ///&lt;br /&gt;&lt;br /&gt;
        ///{1}&lt;br /&gt;&lt;br /&gt;
        ///{2}&lt;br /&gt;&lt;br /&gt;
        ///{3}&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///Regards,&lt;br /&gt;
        ///MagmaLight&lt;br /&gt;
        ///
        ///&lt;/body&gt;
        ///
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ERRORREPORT_BODY {
            get {
                return ResourceManager.GetString("ERRORREPORT_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagmaLight - Error.
        /// </summary>
        internal static string ERRORREPORT_SUBJECT {
            get {
                return ResourceManager.GetString("ERRORREPORT_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;en&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body lang=&quot;en&quot;&gt;
        ///
        ///Dear {0}!&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///You chose the bank transfer for your order, but we haven&apos;t received nor the funds or the payment confirmation. Please verify if the transaction was successful, and if is wasn&apos;t, retry it with the following details:
        ///Amount: {2}&lt;br /&gt;
        ///BIC/SWIFT Code: CIBH HUHB HU88&lt;br /&gt;
        ///IBAN: HU88 1070 0103 5256 7595 5110 000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ORDERNOTPAID_BANKTRANSFER_BODY {
            get {
                return ResourceManager.GetString("ORDERNOTPAID_BANKTRANSFER_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagmaLight - Order {0} - Money request.
        /// </summary>
        internal static string ORDERNOTPAID_BANKTRANSFER_SUBJECT {
            get {
                return ResourceManager.GetString("ORDERNOTPAID_BANKTRANSFER_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;en&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body lang=&quot;en&quot;&gt;
        ///
        ///Dear {0}!&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///You chose the bank card of PayPal payment mehtod, but we haven&apos;t received the funds yet. Please verify if the transaction was completed successfully. If it did not, try it again &lt;a href=&quot;https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&amp;token={4}&quot;&gt;HERE&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;
        ///As soon as we received the money [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ORDERNOTPAID_PAYPAL_BODY {
            get {
                return ResourceManager.GetString("ORDERNOTPAID_PAYPAL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagmaLight - Order {0} - Money request.
        /// </summary>
        internal static string ORDERNOTPAID_PAYPAL_SUBJECT {
            get {
                return ResourceManager.GetString("ORDERNOTPAID_PAYPAL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;en&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body lang=&quot;en&quot;&gt;
        ///
        ///Dear {1}!&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///Thank you for your  order! Your order ID is {0}.&lt;br /&gt;
        ///&lt;br /&gt;
        ///Please make a payment of {2} to the following bank account: &lt;br /&gt;
        ///&lt;br /&gt;
        ///BIC/SWIFT Code: OKHB HUHB&lt;br /&gt;
        ///IBAN: HU96 1040 2506 8675 5490 8378 1009.&lt;br /&gt;
        ///Name of the beneficial: Fuchs Róbert. &lt;br /&gt;
        ///&lt;br /&gt;
        ///Please don&apos;t forget to provide your  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ORDERPLACED_BANKTRANSFER_BODY {
            get {
                return ResourceManager.GetString("ORDERPLACED_BANKTRANSFER_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagmaLight - Order {0}.
        /// </summary>
        internal static string ORDERPLACED_BANKTRANSFER_SUBJECT {
            get {
                return ResourceManager.GetString("ORDERPLACED_BANKTRANSFER_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;en&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body lang=&quot;en&quot;&gt;
        ///
        ///Dear {1}!&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///Thank you for your order! Your order ID is {0}.&lt;br /&gt;
        ///&lt;br /&gt;
        ///You were redirected to our external payment page. Hopefully the payment was completed successfully, otherwise you can try it again &lt;a href=&quot;https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&amp;token={4}&quot;&gt;HERE&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;
        ///As soon as the t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ORDERPLACED_PAYPAL_BODY {
            get {
                return ResourceManager.GetString("ORDERPLACED_PAYPAL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagmaLight - Order {0}.
        /// </summary>
        internal static string ORDERPLACED_PAYPAL_SUBJECT {
            get {
                return ResourceManager.GetString("ORDERPLACED_PAYPAL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;en&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body lang=&quot;en&quot;&gt;
        ///
        ///Dear {1}!&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///Thank you for your order! Your order ID is {0}.&lt;br /&gt;
        ///&lt;br /&gt;
        ///You will get a notification e-mail as soon as we posted your package in 2-3 working days.&lt;br /&gt;
        ///&lt;br /&gt;
        ///You can view the details of your order anytime &lt;a href=&quot;http://www.magmalight.com/Billing/OrderInfo.aspx?OrderID={0}&amp;PassCode={3}&quot;&gt;HERE&lt;/a&gt;.&lt;br  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ORDERPLACED_POST_BODY {
            get {
                return ResourceManager.GetString("ORDERPLACED_POST_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagmaLight - Order {0}.
        /// </summary>
        internal static string ORDERPLACED_POST_SUBJECT {
            get {
                return ResourceManager.GetString("ORDERPLACED_POST_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;en&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body lang=&quot;en&quot;&gt;
        ///
        ///Dear {1}!&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///You package was posted. You will received it in approximately 4-5 working days.&lt;br /&gt;
        ///&lt;br /&gt;
        ///You can view the details of your order and your INVOICE anytime &lt;a href=&quot;http://www.magmalight.com/Billing/OrderInfo.aspx?OrderID={0}&amp;PassCode={3}&quot;&gt;HERE&lt;/a&gt;. (Print it with Ctrl+P keystroke)&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///Tha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PACKAGESENT_BODY {
            get {
                return ResourceManager.GetString("PACKAGESENT_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagmaLight - Order {0} - Package sent.
        /// </summary>
        internal static string PACKAGESENT_SUBJECT {
            get {
                return ResourceManager.GetString("PACKAGESENT_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;en&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body lang=&quot;en&quot;&gt;
        ///
        ///Dear {0}!&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///You password was changed. Your temporary password is &apos;{1}&apos;.&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///Regards,&lt;br /&gt;
        ///MagmaLight&lt;br /&gt;
        ///
        ///&lt;/body&gt;
        ///
        ///&lt;/html&gt;.
        /// </summary>
        internal static string PASSWORDRESET_BODY {
            get {
                return ResourceManager.GetString("PASSWORDRESET_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagmaLight - Change password.
        /// </summary>
        internal static string PASSWORDRESET_SUBJECT {
            get {
                return ResourceManager.GetString("PASSWORDRESET_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;en&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body lang=&quot;en&quot;&gt;
        ///
        ///Dear Webmaster!&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///The customer of the order {0} has sent a recommendation to the followings:&lt;br/&gt;
        ///{1}&lt;br /&gt;
        ///&lt;br /&gt;
        ///The message of the following:&lt;br/&gt;
        ///{2}&lt;br /&gt;
        ///&lt;br /&gt;
        ///It&apos;s important to know, that the forwaring of this message to the recipients is manual!
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///Regards,&lt;br /&gt;
        ///MagmaLight&lt;br /&gt;
        ///
        ///&lt;/body&gt;
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RECOMMENDATION_BODY {
            get {
                return ResourceManager.GetString("RECOMMENDATION_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagmaLight - Recommendation.
        /// </summary>
        internal static string RECOMMENDATION_SUBJECT {
            get {
                return ResourceManager.GetString("RECOMMENDATION_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;en&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body lang=&quot;en&quot;&gt;
        ///
        ///Dear {1}!&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///We hope that you have already received our products and you started to used them! It would be a great help for us, if you could fill our 1-minute survey to help us improve our services!&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;a href=&quot;http://www.magmalight.com/Admin/ShowSurvey.aspx?OrderID={0}&amp;ConfirmationCode={2}&amp;SurveyID={3}&quot;&gt;Please  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SURVEYREQUEST_BODY {
            get {
                return ResourceManager.GetString("SURVEYREQUEST_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagmaLight - Survey.
        /// </summary>
        internal static string SURVEYREQUEST_SUBJECT {
            get {
                return ResourceManager.GetString("SURVEYREQUEST_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;en&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body lang=&quot;en&quot;&gt;
        ///
        ///Dear Webmaster!&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///The order with order ID of {0} had an unusual status change from value {1} to value {2}.&lt;br /&gt;
        ///&lt;br /&gt;
        ///You can view the details of your order anytime &lt;a href=&quot;http://www.magmalight.com/Billing/OrderInfo.aspx?OrderID={0}&amp;PassCode={3}&quot;&gt;HERE&lt;/a&gt;.&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///Regards,&lt;br /&gt;
        ///MagmaLight&lt;br /&gt;
        ///
        ///&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UNKNOWNSTATUSCHANGE_BODY {
            get {
                return ResourceManager.GetString("UNKNOWNSTATUSCHANGE_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagmaLight - Status change.
        /// </summary>
        internal static string UNKNOWNSTATUSCHANGE_SUBJECT {
            get {
                return ResourceManager.GetString("UNKNOWNSTATUSCHANGE_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;en&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body lang=&quot;en&quot;&gt;
        ///
        ///Dear Webmaster!&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///At {2} someone sent you a message through our web-site. He/she provided &apos;{0}&apos; as an e-mail address and the message is the following:&lt;br /&gt;
        ///&lt;br /&gt;
        ///{1}&lt;br/&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///Regards,&lt;br /&gt;
        ///MagmaLight&lt;br /&gt;
        ///
        ///&lt;/body&gt;
        ///
        ///&lt;/html&gt;.
        /// </summary>
        internal static string WEBMAIL_BODY {
            get {
                return ResourceManager.GetString("WEBMAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagmaLight - Webmail.
        /// </summary>
        internal static string WEBMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("WEBMAIL_SUBJECT", resourceCulture);
            }
        }
    }
}
