//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Products {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Products() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Products", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystalbeam bulb E27 25W.
        /// </summary>
        internal static string LOC_ES002W_DESC {
            get {
                return ResourceManager.GetString("LOC_ES002W_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystalbeam bulb E27 25W.
        /// </summary>
        internal static string LOC_ES002_DESC {
            get {
                return ResourceManager.GetString("LOC_ES002_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunbeam bulb E27 23W.
        /// </summary>
        internal static string LOC_ES004_DESC {
            get {
                return ResourceManager.GetString("LOC_ES004_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystalbeam bulb E14 15W.
        /// </summary>
        internal static string LOC_ES015W_DESC {
            get {
                return ResourceManager.GetString("LOC_ES015W_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystalbeam bulb E14 15W.
        /// </summary>
        internal static string LOC_ES015_DESC {
            get {
                return ResourceManager.GetString("LOC_ES015_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package costs.
        /// </summary>
        internal static string LOC_PACKAGECOST {
            get {
                return ResourceManager.GetString("LOC_PACKAGECOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending costs.
        /// </summary>
        internal static string LOC_SENDINGCOST {
            get {
                return ResourceManager.GetString("LOC_SENDINGCOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction costs.
        /// </summary>
        internal static string LOC_TRANSACTIONCOST {
            get {
                return ResourceManager.GetString("LOC_TRANSACTIONCOST", resourceCulture);
            }
        }
    }
}
