//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PaymentMethods {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentMethods() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PaymentMethods", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string PAYMENTMETHOD_0 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank transfer.
        /// </summary>
        internal static string PAYMENTMETHOD_1 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal.
        /// </summary>
        internal static string PAYMENTMETHOD_2 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card.
        /// </summary>
        internal static string PAYMENTMETHOD_3 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string PAYMENTMETHOD_4 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string PAYMENTMETHOD_5 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitCoin.
        /// </summary>
        internal static string PAYMENTMETHOD_6 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwolla.
        /// </summary>
        internal static string PAYMENTMETHOD_7 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneybookers.
        /// </summary>
        internal static string PAYMENTMETHOD_8 {
            get {
                return ResourceManager.GetString("PAYMENTMETHOD_8", resourceCulture);
            }
        }
    }
}
