//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Products {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Products() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Products", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Full spectrum (CRI 80+) bulb with ionizer&lt;p/&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;p/&gt;
        ///&lt;p&gt;18W (max. 25W at startup)&lt;/p&gt;
        ///&lt;p&gt;1500 lumen (normal 110W brightness)&lt;p/&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;p/&gt;
        ///&lt;p&gt;6500 Kelvin or 2700 Kelvin&lt;p/&gt;
        ///&lt;p&gt;3 million -ion/s (without ozone prod.)&lt;p/&gt;
        ///&lt;p&gt;8,000 hours average lifespan&lt;p/&gt;
        ///&lt;p&gt;220-240V - socket E27&lt;p/&gt;
        ///&lt;p&gt;Dims (length x diam): 155mm x 57mm&lt;p/&gt;.
        /// </summary>
        internal static string LOC_ES002W_DESC {
            get {
                return ResourceManager.GetString("LOC_ES002W_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystalbeam bulb.
        /// </summary>
        internal static string LOC_ES002W_NAME {
            get {
                return ResourceManager.GetString("LOC_ES002W_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18W, 1500 lumen, 2700 Kelvin.
        /// </summary>
        internal static string LOC_ES002W_ONELINER {
            get {
                return ResourceManager.GetString("LOC_ES002W_ONELINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Full spectrum (CRI 80+) bulb with ionizer&lt;p/&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;p/&gt;
        ///&lt;p&gt;18W (max. 25W at startup)&lt;/p&gt;
        ///&lt;p&gt;1500 lumen (normal 110W brightness)&lt;p/&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;p/&gt;
        ///&lt;p&gt;6500 Kelvin or 2700 Kelvin&lt;p/&gt;
        ///&lt;p&gt;3 million -ion/s (without ozone prod.)&lt;p/&gt;
        ///&lt;p&gt;8,000 hours average lifespan&lt;p/&gt;
        ///&lt;p&gt;220-240V - socket E27&lt;p/&gt;
        ///&lt;p&gt;Dims (length x diam): 155mm x 57mm&lt;p/&gt;.
        /// </summary>
        internal static string LOC_ES002_DESC {
            get {
                return ResourceManager.GetString("LOC_ES002_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystalbeam bulb.
        /// </summary>
        internal static string LOC_ES002_NAME {
            get {
                return ResourceManager.GetString("LOC_ES002_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18W, 1500 lumen, 6500 Kelvin.
        /// </summary>
        internal static string LOC_ES002_ONELINER {
            get {
                return ResourceManager.GetString("LOC_ES002_ONELINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Full spectrum (CRI 90+) bulb&lt;p/&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;p/&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;p/&gt;
        ///&lt;p&gt;13W (max. 23W at startup)&lt;p/&gt;
        ///&lt;p&gt;1150 lumen (normal 85W brightness)&lt;p/&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;p/&gt;
        ///&lt;p&gt;5800 Kelvin&lt;p/&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;p/&gt;
        ///&lt;p&gt;8,000 hours average lifespan&lt;p/&gt;
        ///&lt;p&gt;220-240V - socket E27&lt;p/&gt;
        ///&lt;p&gt;Dims (length x diam): 140mm x 57mm&lt;p/&gt;.
        /// </summary>
        internal static string LOC_ES004_DESC {
            get {
                return ResourceManager.GetString("LOC_ES004_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunbeam bulb.
        /// </summary>
        internal static string LOC_ES004_NAME {
            get {
                return ResourceManager.GetString("LOC_ES004_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13W, 1150 lumen, 5800 Kelvin.
        /// </summary>
        internal static string LOC_ES004_ONELINER {
            get {
                return ResourceManager.GetString("LOC_ES004_ONELINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Full spectrum (CRI 80+) bulb with ionizer&lt;p/&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;p/&gt;
        ///&lt;p&gt;9W (max 15W at startup)&lt;p/&gt;
        ///&lt;p&gt;900 lumen (normal 65W brightness)&lt;p/&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;p/&gt;
        ///&lt;p&gt;6500 Kelvin or 2700 Kelvin&lt;p/&gt;
        ///&lt;p&gt;3 million -ion/s (without ozone prod.)&lt;p/&gt;
        ///&lt;p&gt;8,000 hours average lifespan&lt;p/&gt;
        ///&lt;p&gt;220-240V - socket E14&lt;p/&gt;
        ///&lt;p&gt;Dims (length x diam): 127mm x 40mm&lt;p/&gt;.
        /// </summary>
        internal static string LOC_ES015W_DESC {
            get {
                return ResourceManager.GetString("LOC_ES015W_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystalbeam bulb E14.
        /// </summary>
        internal static string LOC_ES015W_NAME {
            get {
                return ResourceManager.GetString("LOC_ES015W_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9W, 900 lumen, 2700 Kelvin.
        /// </summary>
        internal static string LOC_ES015W_ONELINER {
            get {
                return ResourceManager.GetString("LOC_ES015W_ONELINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Full spectrum (CRI 80+) bulb with ionizer&lt;p/&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;p/&gt;
        ///&lt;p&gt;9W (max 15W at startup)&lt;p/&gt;
        ///&lt;p&gt;900 lumen (normal 65W brightness)&lt;p/&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;p/&gt;
        ///&lt;p&gt;6400 Kelvin or 2700 Kelvin&lt;p/&gt;
        ///&lt;p&gt;3 million -ion/s (without ozone prod.)&lt;p/&gt;
        ///&lt;p&gt;8,000 hours average lifespan&lt;p/&gt;
        ///&lt;p&gt;220-240V - socket E14&lt;p/&gt;
        ///&lt;p&gt;Dims (length x diam): 127mm x 40mm&lt;p/&gt;.
        /// </summary>
        internal static string LOC_ES015_DESC {
            get {
                return ResourceManager.GetString("LOC_ES015_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystalbeam bulb E14.
        /// </summary>
        internal static string LOC_ES015_NAME {
            get {
                return ResourceManager.GetString("LOC_ES015_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9W, 900 lumen, 6500 Kelvin.
        /// </summary>
        internal static string LOC_ES015_ONELINER {
            get {
                return ResourceManager.GetString("LOC_ES015_ONELINER", resourceCulture);
            }
        }
    }
}
