//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Surveys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Surveys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Surveys", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey about your order.
        /// </summary>
        internal static string SURVEY_AFTERORDER {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you think it is enough information on the website?.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q1_RDB {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q1_RDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q1_RDB_OPT1 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q1_RDB_OPT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too few.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q1_RDB_OPT2 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q1_RDB_OPT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount I&apos;d expect.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q1_RDB_OPT3 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q1_RDB_OPT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disturbingly too much.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q1_RDB_OPT4 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q1_RDB_OPT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was it easy to find what you were looking for?.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q2_RDB {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q2_RDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The structure of the site is not good.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q2_RDB_OPT1 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q2_RDB_OPT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is alright, but could be better.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q2_RDB_OPT2 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q2_RDB_OPT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve found everything I wanted.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q2_RDB_OPT3 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q2_RDB_OPT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was the assistance quick?.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q3_RDB {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q3_RDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I&apos;d expect faster responses.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q3_RDB_OPT1 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q3_RDB_OPT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptable.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q3_RDB_OPT2 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q3_RDB_OPT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response was fast, I got my product quickly.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q3_RDB_OPT3 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q3_RDB_OPT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How satified are you with the product?.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q4_RDB {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q4_RDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I did expect something else.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q4_RDB_OPT1 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q4_RDB_OPT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I expected something better, I&apos;m not satisfied with quality.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q4_RDB_OPT2 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q4_RDB_OPT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I expected something better, I&apos;m not satisfied with light.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q4_RDB_OPT3 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q4_RDB_OPT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I expected it to be like this, but I am not amazed.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q4_RDB_OPT4 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q4_RDB_OPT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I love it, I would recommend it to others as well.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q4_RDB_OPT5 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q4_RDB_OPT5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was our team helpful, when you asked for help?.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q5_RDB {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q5_RDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t ask for help.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q5_RDB_OPT1 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q5_RDB_OPT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I asked for help, but the answer was not satisfying.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q5_RDB_OPT2 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q5_RDB_OPT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I asked for help, but the response was slow.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q5_RDB_OPT3 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q5_RDB_OPT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I asked for help, and the answer was fast and accurate.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q5_RDB_OPT4 {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q5_RDB_OPT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any suggestion how to make our service better?.
        /// </summary>
        internal static string SURVEY_AFTERORDER_Q6_TXT {
            get {
                return ResourceManager.GetString("SURVEY_AFTERORDER_Q6_TXT", resourceCulture);
            }
        }
    }
}
